import {CommonModule} from '@angular/common';
import {FormsModule, ReactiveFormsModule} from '@angular/forms';

import {
    AccordionModule,
    ButtonModule,
    CalendarModule,
    CheckboxModule,
    DropdownModule,
    FieldsetModule,
    InputMaskModule,
    InputSwitchModule,
    InputTextModule,
    InputTextareaModule,
    EditorModule,
    PasswordModule,
    SelectButtonModule,
    TabViewModule,
    TreeModule,
    ToolbarModule,
    FileUploadModule,
    SpinnerModule,
    DragDropModule,
    MultiSelectModule,
    AutoCompleteModule,
    ConfirmDialogModule,
    GrowlModule,
    MessagesModule,
    MessageModule,
    BlockUIModule,
    ProgressBarModule,
    TreeTableModule,
    PanelModule,
    ToggleButtonModule,
    TooltipModule,
    OverlayPanelModule,
    SliderModule,
    RadioButtonModule,
    SplitButtonModule,
    OrderListModule,
    DialogModule,
    SidebarModule,
    ChartModule,
    PickListModule,
    ScrollPanelModule,
    MenuModule

} from 'primeng/primeng';

import {ToastModule} from 'primeng/toast';
import {TableModule} from 'primeng/table';
import {DynamicDialogModule} from 'primeng/dynamicdialog';
import {TabMenuModule} from 'primeng/tabmenu';
import {TranslateModule} from '@ngx-translate/core';

export const sharedExports = [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    AccordionModule,
    ButtonModule,
    CalendarModule,
    CheckboxModule,
    DropdownModule,
    FieldsetModule,
    InputMaskModule,
    InputSwitchModule,
    InputTextModule,
    InputTextareaModule,
    EditorModule,
    PasswordModule,
    SelectButtonModule,
    TabViewModule,
    TreeModule,
    ToolbarModule,
    ToastModule,
    TableModule,
    FileUploadModule,
    SpinnerModule,
    DragDropModule,
    MultiSelectModule,
    AutoCompleteModule,
    ConfirmDialogModule,
    GrowlModule,
    MessageModule,
    MessagesModule,
    BlockUIModule,
    ProgressBarModule,
    TreeTableModule,
    PanelModule,
    ToggleButtonModule,
    TooltipModule,
    OverlayPanelModule,
    SliderModule,
    ChartModule,
    TableModule,
    RadioButtonModule,
    SplitButtonModule,
    OrderListModule,
    SidebarModule,
    DialogModule,
    PickListModule,
    ScrollPanelModule,
    TranslateModule,
    DynamicDialogModule,
    TabMenuModule,
    MenuModule
];
